### ISSUE TITLE
Get version switcher and version sorting working

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/docs.matflow.io#1]
Version switcher currently doesn't work.

Implement fixes form:
https://github.com/hpcflow/hpcflow.github.io/issues/1
https://github.com/hpcflow/hpcflow.github.io/issues/4

**Comment by cjfullerton** [comment]
Also not working again in hpcflow.

**Comment by aplowman** [comment]
> Also not working again in hpcflow.

Actually, I had to downgrade Sphinx (to 6) from what I had initially upgraded it to (7) in my docs branch, and the warning I had mentioned previously has disappeared. So, it's working fine in hpcflow now, and we just need to update MatFlow I think
